### ISSUE TITLE
Incorrect merged text when using big client IDs

### ISSUE THREAD

**Issue by zaynetro** [y-crdt/y-crdt#221]
Hi!

I am playing around with concurrent text updates and noticed a case when state diverges on two clients when using big ClientIDs.

The docs say that ClientID is:
> Globally unique 53-bit long client identifier.

But it seems that in practice it is u32: https://github.com/y-crdt/y-crdt/issues/209

It would be nice to at least fail when trying to use ClientIDs that are too big. Otherwise, you might not even notice the problem.

Sample test for Yrs version 0.13:

```rust
#[test]
fn test_yjs_client_id_bug() {
    // Fails with these client IDs:
    let client_id_a = 213270268221190;
    let client_id_b = 221179227290192;
    // Works with these client IDs:
    // let client_id_a = 2132702682;
    // let client_id_b = 2211792272;

    // Create doc on device A
    let doc_a = yrs::Doc::with_client_id(client_id_a);
    let text_a = doc_a.get_or_insert_text("text");
    {
        let txn = &mut doc_a.transact_mut();
        text_a.insert(txn, 0, "Hello world!");
    }
    // Encode update from A to B
    let update_ab = {
        let txn = doc_a.transact();
        txn.encode_state_as_update_v2(&StateVector::default())
    };

    // Read doc on device B
    let doc_b = yrs::Doc::with_client_id(client_id_b);
    {
        let txn = &mut doc_b.transact_mut();
        txn.apply_update(Update::decode_v2(&update_ab).unwrap());
    }

    // Modify doc concurrently on A and B
    let text_b = doc_b.get_or_insert_text("text");
    {
        let txn = &mut doc_a.transact_mut();
        text_a.insert(txn, 11, " and Good luck");
        assert_eq!("Hello world and Good luck!", text_a.get_string(txn));
    }
    {
        let txn = &mut doc_b.transact_mut();
        text_b.remove_range(txn, 1, 4);
        text_b.insert(txn, 1, "i");
        assert_eq!("Hi world!", text_b.get_string(txn));
    }

    // Merge A's changes on B
    let expected = "Hi world and Good luck!";
    {
        let txn_a = doc_a.transact();
        let update_ab = txn_a.encode_state_as_update_v2(&StateVector::default());

        let txn_b = &mut doc_b.transact_mut();
        txn_b.apply_update(Update::decode_v2(&update_ab).unwrap());

        // This one is correct
        assert_eq!(expected, text_b.get_string(txn_b));
    }

    // Merge B's changes on A
    {
        let txn_b = doc_b.transact();
        let update_ba = txn_b.encode_state_as_update_v2(&StateVector::default());

        let txn_a = &mut doc_a.transact_mut();
        txn_a.apply_update(Update::decode_v2(&update_ba).unwrap());

        // Fails here
        assert_eq!(expected, text_a.get_string(txn_a));
    }
}
```

Fails with:

```
thread 'tests::test_yjs_client_id_bug' panicked at 'assertion failed: `(left == right)`
  left: `"Hi world and Good luck!"`,
 right: `"Helloi world and Good luck!"`', 
```

**Comment by Horusiath** [comment]
Thanks for the reproduction scenario. Yes, in fact Yrs is using u31 (for the sake of compatibility with Yjs). 53bits are waiting for their turn, as this change must be coordinated between two projects (see: #110).

**Comment by Horusiath** [comment]
Should be fixed now - we moved to 53bit ints (together with Yjs) some time ago.

**Comment by federico-terzi** [comment]
Hi folks!
@Horusiath I've tried re-running the reproduction case reported by @zaynetro, but it's still failing on the latest version (0.17.1), so probably we should re-open the issue?

**Comment by conradludgate** [comment]
Hi, I encountered this issue as well. It seems to be related to negative numbers. Here's a new repro on yrs 0.25.0

```rust
use yrs::updates::decoder::Decode;
use yrs::{Doc, GetString, ReadTxn, StateVector, Text, Transact, Update};

fn v2_roundtrip(client_id: u64) {
    let doc = Doc::with_client_id(client_id);
    let text = doc.get_or_insert_text("t");
    {
        let mut txn = doc.transact_mut();
        text.insert(&mut txn, 0, "hello");
    }

    let encoded = doc.transact().encode_diff_v2(&StateVector::default());
    let update = Update::decode_v2(&encoded)
        .unwrap_or_else(|e| panic!("decode_v2 failed for client_id {client_id:#x}: {e}"));

    let doc2 = Doc::new();
    let text2 = doc2.get_or_insert_text("t");
    doc2.transact_mut().apply_update(update).unwrap();
    assert_eq!(text2.get_string(&doc2.transact()), "hello");
}

#[test]
fn v2_works_below_i64_max() {
    v2_roundtrip(0);
    v2_roundtrip(1);
    v2_roundtrip(u64::from(u32::MAX));
    v2_roundtrip(i64::MAX as u64); // 2^63 - 1 — largest working value
}

#[test]
#[should_panic(expected = "attempt to negate with overflow")]
fn v2_encode_panics_at_i64_min() {
    v2_roundtrip(i64::MIN as u64); // 2^63
}

#[test]
#[should_panic(expected = "decode_v2 failed for client_id 0x8000000000000001: while trying to read more data (expected: 1 bytes), an unexpected end of buffer was reached")]
fn v2_decode_fails_above_i64_max() {
    v2_roundtrip(i64::MIN as u64 + 1); // 2^63 + 1
}
```

**Comment by conradludgate** [comment]
Ok. Apparently if I expand my test above to include removals, it no longer works with client IDs >32 bits.

**Comment by Horusiath** [comment]
Yes, the thing is yjs by [default uses 32bit](https://github.com/yjs/yjs/blob/db29b422638df4c4a5a4b87bfb2e3dcd8406b517/src/utils/Doc.js#L20) long ClientID. Overtime there was a regression in one of the yrs versions, where we mapped `u64`&rarr;`u32` when reading updates, which passed silently as long as `u64` client ID was present remotely not locally. 

However after fixing this problem (so mapping back to original `u64`) it turned out that some of the document updates are irrecoverably malformed - making them unreadable. The issue was that - when reading using lib0 v1 encoding - once you read ID as `u32`, you still can read the document and insert new elements. However these elements will now refer to their neighbours using ID represented as `u32`. Then if we introduce the fix and try to read the document, we'll no longer be able to find neighbours of recently written data (because we used truncated 32bit ids to refer to elements that now are identified using 64 bits), and we won't be able to read the document any longer.

If you really need to use 64bit client IDs, I think we could introduce a cargo feature flag for that. But honestly, if 32bits are not enough, that could be the sign of more serious underlying issues in your app.

**Comment by conradludgate** [comment]
The concern of 32bit IDs is most regarding birthday paradox. Random 32bit IDs have a fairly high chance of collision. With 65536 client IDs you have a 50% chance of collision. That's a lot of clients on the same document, but not unreasonable. With 256 clients there's a 0.001% chance of collision which is low but not negligible - It will happen. 

It fundamentally means you need to maintain a list of client IDs and assign them, rather than relying on RNG. Might be a good idea for a service anyway, but it's a bit of a challenge for my application which is p2p.

Fortunately I was able to implement client ID uniqueness and allowed trying to rejoin with a new IV seed, so not a huge blocker for me.

---

I think it would be better to make sure you either error clearly on large IDs, or truncate them properly in all the places that matter. Debugging these issues is really challenging

**Comment by Horusiath** [comment]
> Random 32bit IDs have a fairly high chance of collision. With 65536 client IDs you have a 50% chance of collision. That's a lot of clients on the same document, but not unreasonable.

1. It is unreasonable. It means that the state vectors - which are essentially causal timestamps - can run into hundreds of KB.  If you're using yrs on native client, you can think of recycling them between sessions (as long as you can guarantee than no two processes will use the same clientID at the same time).
2. This collision matters only when you have clients using the same ID who are either:
    - Alive at the same time (and making updates).
    - Out of sync (some updates from one client didn't reach another using the same ID).

The reason why client ID shouldn't be duplicated is because it could generate a duplicate update identifier with different user data, causing the unresolvable conflict (since update blocks are deduplicated by ID). If you use client ID of a dead process that won't be used to insert new data, that's not a problem.

> It fundamentally means you need to maintain a list of client IDs and assign them, rather than relying on RNG.

Client IDs are var-int encoded. We made a test for low-range IDs and it turned out that they can reduce overall update size by up to 30% (tested on v1 encoding). So if you are able to establish clientID from the outside, that could have some benefits.
